---
Gigabit:
  Ethernet:
    - Int: "0/0"
      IP: "10.0.10.2 255.255.255.252"
      Desc: "vEdge Link"

    - Int: "0/1"
      IP: "10.0.10.6 255.255.255.252"
      Desc: "vEdge Link"

Loopback:
  LoopbackNum:
    - Int: "1"
      IP: "1.1.1.1 255.255.255.255"
      Desc: "LAN 1"

    - Int: "11"
      IP: "11.11.11.11 255.255.255.255"
      Desc: "LAN 11"

OSPF:
  process: "1"
  network:
    - net0: "10.0.10.0 0.0.0.3 area 0"
      net1: "10.0.10.4 0.0.0.3 area 0"
      net2: "1.1.1.1 0.0.0.0 area 0"
      net3: "11.11.11.11 0.0.0.0 area 0"